// next
import Head from 'next/head'
// react
import { useEffect, useRef } from "react"
// components
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Hero from "@/components/home/Hero"
import Plan from "@/components/home/Plan"
import QA from "@/components/home/QA"
import SignUp from "@/components/home/SignUp"

export default () => {
  const mainRef = useRef<HTMLDivElement>(null)

  useEffect(()=>{
    mainRef.current!.style.marginTop = `${-1 * document.querySelector("header")!.offsetHeight}px`
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main ref={mainRef}>
        <Hero />
        <Plan />
        <QA />
        <SignUp />
      </main>
      <Footer />
    </>
  )
}